input_params <- list(T=180, 
                     prob_medic_has_it_already=0.001, 
                     prob_patient_has_it_already=0.001, 
                     prob_doctor_patient_transmission=0.15, 
                     prob_patient_doctor_transmission=0.15, 
                     prob_patient_nurse_transmission=0.2, 
                     prob_nurse_patient_transmission=0.2, 
                     days_out_doc=21, 
                     prob_doc_critically_ill=0.07, 
                     community_transmission_prob=0.0003, 
                     inc_minus_latent=1, 
                     npatients_init=15, 
                     average_patient_stay=3, 
                     lognormal_param1=1.63, 
                     lognormal_param2=0.673, 
                     days_past_symptom_patient_infective=1, 
                     medic_medic_transmission_probability_factor=0.07, 
                     maximum_hours_per_week_nurse=48, 
                     n_attendings=3, 
                     n_residents=6, 
                     n_nurses=18, 
                     n_attentings_at_once=1, 
                     n_residents_at_once=2, 
                     n_nurses_at_once=3)

sim_output <- COVID_sim9(length_rotation=3,
                         length_rotation_n=3,
                         nspd=2,
                         staggering=FALSE,
                         input_params=input_params,nit=100) # try small run time
sim_output
